name: corona
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.0
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.4
  cached_network_image: ^3.2.0
  webview_flutter: ^3.0.1
  carousel_slider: ^4.0.0
  rect_getter: ^1.1.0
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2
  auto_size_text: ^3.0.0
  another_flushbar: ^1.10.28
  device_preview: ^1.0.0
  flutter_native_splash: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # launcher names
  flutter_app_name: ^0.1.1

# app name
flutter_app_name:
  name: "Corona Updates"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  image_path: "assets/launcher/launcher.png"

# native splash screen
flutter_native_splash:
  background_image: "assets/welcome/splash_screen.png"
  background_image_dark: "assets/welcome/splash_screen.png"
  image: "assets/launcher/launcher.png"
  image_dark: "assets/launcher/launcher.png"
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/symptoms/
    - assets/
    - assets/prevention/
    - assets/myths/
    - assets/updates/
    - assets/stats/
    - assets/flags/
    - assets/launcher/
    - assets/welcome/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
